### ISSUE TITLE
Does not build with lomse 0.26.0

### ISSUE THREAD

**Issue by luigino** [lenmus/lenmus#68]
As per subject, trying to build lenmus 5.4.2 on openSUSE Tumbleweed and I'm seeing the following error:

```
[  2%] Building CXX object CMakeFiles/lenmus.dir/src/app/lenmus_app.cpp.o
/usr/bin/c++  -DGCC -DWXUSINGDLL -D_FILE_OFFSET_BITS=64 -D__UNIX__ -D__WXGTK__ -DwxDEBUG_LEVEL=0 -I/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/include -I/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/packages/wxMidi/src -I/usr/include/unittest-cpp -I/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/packages/wxSQLite3/include -I/usr/include/lomse -I/usr/include/freetype2 -I/usr/include/libpng16 -I/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/build -isystem /usr/lib64/wx/include/gtk2-unicode-3.0 -isystem /usr/include/wx-3.0  -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG -pthread -O2 -g -DNDEBUG   -Wall -o CMakeFiles/lenmus.dir/src/app/lenmus_app.cpp.o -c /home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/src/app/lenmus_app.cpp
In file included from /home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/include/lenmus_main_frame.h:29,
                 from /home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/src/app/lenmus_app.cpp:25:
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/include/lenmus_events.h:57:5: error: 'SpEventScoreHighlight' does not name a type
   57 |     SpEventScoreHighlight m_pEvent;   //lomse event
      |     ^~~~~~~~~~~~~~~~~~~~~
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/include/lenmus_events.h:60:48: error: expected ')' before 'pEvent'
   60 |     lmScoreHighlightEvent(SpEventScoreHighlight pEvent, int id = 0)
      |                          ~                     ^~~~~~~
      |                                                )
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/include/lenmus_events.h:77:5: error: 'SpEventScoreHighlight' does not name a type
   77 |     SpEventScoreHighlight get_lomse_event() { return m_pEvent; }
      |     ^~~~~~~~~~~~~~~~~~~~~
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/include/lenmus_events.h: In copy constructor 'lenmus::lmScoreHighlightEvent::lmScoreHighlightEvent(const lenmus::lmScoreHighlightEvent&)':
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/include/lenmus_events.h:69:11: error: class 'lenmus::lmScoreHighlightEvent' does not have any field named 'm_pEvent'
   69 |         , m_pEvent( event.m_pEvent )
      |           ^~~~~~~~
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/include/lenmus_events.h:69:27: error: 'const class lenmus::lmScoreHighlightEvent' has no member named 'm_pEvent'
   69 |         , m_pEvent( event.m_pEvent )
      |                           ^~~~~~~~
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/include/lenmus_events.h: At global scope:
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/include/lenmus_events.h:97:5: error: 'SpEventPlayScore' does not name a type
   97 |     SpEventPlayScore m_pEvent;   //lomse event
      |     ^~~~~~~~~~~~~~~~
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/include/lenmus_events.h:100:42: error: expected ')' before 'pEvent'
  100 |     lmEndOfPlaybackEvent(SpEventPlayScore pEvent, int id = 0 )
      |                         ~                ^~~~~~~
      |                                          )
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/include/lenmus_events.h:117:5: error: 'SpEventPlayScore' does not name a type
  117 |     SpEventPlayScore get_lomse_event() { return m_pEvent; }
      |     ^~~~~~~~~~~~~~~~
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/include/lenmus_events.h: In copy constructor 'lenmus::lmEndOfPlaybackEvent::lmEndOfPlaybackEvent(const lenmus::lmEndOfPlaybackEvent&)':
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/include/lenmus_events.h:109:11: error: class 'lenmus::lmEndOfPlaybackEvent' does not have any field named 'm_pEvent'
  109 |         , m_pEvent( event.m_pEvent )
      |           ^~~~~~~~
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/include/lenmus_events.h:109:27: error: 'const class lenmus::lmEndOfPlaybackEvent' has no member named 'm_pEvent'
  109 |         , m_pEvent( event.m_pEvent )
      |                           ^~~~~~~~
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/src/app/lenmus_app.cpp: At global scope:
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/src/app/lenmus_app.cpp:69:50: note: #pragma message: Using boost shared pointers
   69 |     #pragma message("Using boost shared pointers")
      |                                                  ^
In file included from /usr/include/lomse/lomse_internal_model.h:47,
                 from /usr/include/lomse/lomse_document.h:37,
                 from /usr/include/lomse/lomse_metronome.h:33,
                 from /home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/include/lenmus_injectors.h:34,
                 from /home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/include/lenmus_app.h:26,
                 from /home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/src/app/lenmus_app.cpp:22:
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/src/app/lenmus_app.cpp: In member function 'void lenmus::TheApp::check_for_updates()':
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/src/app/lenmus_app.cpp:470:37: error: 'boost' has not been declared
  470 |                 LOMSE_LOG_ERROR(str(boost::format(
      |                                     ^~~~~
/usr/include/lomse/lomse_logger.h:58:96: note: in definition of macro 'LOMSE_LOG_ERROR'
   58 | #define LOMSE_LOG_ERROR(...)            logger.log_error(__FILE__,__LINE__,__PRETTY_FUNCTION__,__VA_ARGS__)
      |                                                                                                ^~~~~~~~~~~
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/src/app/lenmus_app.cpp:470:33: error: 'str' was not declared in this scope; did you mean 'std'?
  470 |                 LOMSE_LOG_ERROR(str(boost::format(
      |                                 ^~~
/usr/include/lomse/lomse_logger.h:58:96: note: in definition of macro 'LOMSE_LOG_ERROR'
   58 | #define LOMSE_LOG_ERROR(...)            logger.log_error(__FILE__,__LINE__,__PRETTY_FUNCTION__,__VA_ARGS__)
      |                                                                                                ^~~~~~~~~~~
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/src/app/lenmus_app.cpp: In member function 'void lenmus::TheApp::set_up_locale(wxString)':
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/src/app/lenmus_app.cpp:666:28: error: 'boost' has not been declared
  666 |         LOMSE_LOG_INFO(str(boost::format("Language '%s' not found. Update TheApp.cpp?")
      |                            ^~~~~
/usr/include/lomse/lomse_logger.h:60:95: note: in definition of macro 'LOMSE_LOG_INFO'
   60 | #define LOMSE_LOG_INFO(...)             logger.log_info(__FILE__,__LINE__,__PRETTY_FUNCTION__,__VA_ARGS__)
      |                                                                                               ^~~~~~~~~~~
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/src/app/lenmus_app.cpp:666:24: error: 'str' was not declared in this scope; did you mean 'std'?
  666 |         LOMSE_LOG_INFO(str(boost::format("Language '%s' not found. Update TheApp.cpp?")
      |                        ^~~
/usr/include/lomse/lomse_logger.h:60:95: note: in definition of macro 'LOMSE_LOG_INFO'
   60 | #define LOMSE_LOG_INFO(...)             logger.log_info(__FILE__,__LINE__,__PRETTY_FUNCTION__,__VA_ARGS__)
      |                                                                                               ^~~~~~~~~~~
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/src/app/lenmus_app.cpp:688:32: error: 'boost' has not been declared
  688 |             LOMSE_LOG_INFO(str(boost::format("Failure to load catalog '%s'. Path='%s'")
      |                                ^~~~~
/usr/include/lomse/lomse_logger.h:60:95: note: in definition of macro 'LOMSE_LOG_INFO'
   60 | #define LOMSE_LOG_INFO(...)             logger.log_info(__FILE__,__LINE__,__PRETTY_FUNCTION__,__VA_ARGS__)
      |                                                                                               ^~~~~~~~~~~
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/src/app/lenmus_app.cpp:688:28: error: 'str' was not declared in this scope; did you mean 'std'?
  688 |             LOMSE_LOG_INFO(str(boost::format("Failure to load catalog '%s'. Path='%s'")
      |                            ^~~
/usr/include/lomse/lomse_logger.h:60:95: note: in definition of macro 'LOMSE_LOG_INFO'
   60 | #define LOMSE_LOG_INFO(...)             logger.log_info(__FILE__,__LINE__,__PRETTY_FUNCTION__,__VA_ARGS__)
      |                                                                                               ^~~~~~~~~~~
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/src/app/lenmus_app.cpp:692:32: error: 'boost' has not been declared
  692 |             LOMSE_LOG_INFO(str(boost::format("Failure to load catalog '%s'. Path='%s'")
      |                                ^~~~~
/usr/include/lomse/lomse_logger.h:60:95: note: in definition of macro 'LOMSE_LOG_INFO'
   60 | #define LOMSE_LOG_INFO(...)             logger.log_info(__FILE__,__LINE__,__PRETTY_FUNCTION__,__VA_ARGS__)
      |                                                                                               ^~~~~~~~~~~
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/src/app/lenmus_app.cpp:692:28: error: 'str' was not declared in this scope; did you mean 'std'?
  692 |             LOMSE_LOG_INFO(str(boost::format("Failure to load catalog '%s'. Path='%s'")
      |                            ^~~
/usr/include/lomse/lomse_logger.h:60:95: note: in definition of macro 'LOMSE_LOG_INFO'
   60 | #define LOMSE_LOG_INFO(...)             logger.log_info(__FILE__,__LINE__,__PRETTY_FUNCTION__,__VA_ARGS__)
      |                                                                                               ^~~~~~~~~~~
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/src/app/lenmus_app.cpp:696:32: error: 'boost' has not been declared
  696 |             LOMSE_LOG_INFO(str(boost::format("Failure to load catalog '%s'. Path='%s'")
      |                                ^~~~~
/usr/include/lomse/lomse_logger.h:60:95: note: in definition of macro 'LOMSE_LOG_INFO'
   60 | #define LOMSE_LOG_INFO(...)             logger.log_info(__FILE__,__LINE__,__PRETTY_FUNCTION__,__VA_ARGS__)
      |                                                                                               ^~~~~~~~~~~
/home/abuild/rpmbuild/BUILD/lenmus-Release_5.4.2/src/app/lenmus_app.cpp:696:28: error: 'str' was not declared in this scope; did you mean 'std'?
  696 |             LOMSE_LOG_INFO(str(boost::format("Failure to load catalog '%s'. Path='%s'")
      |                            ^~~
/usr/include/lomse/lomse_logger.h:60:95: note: in definition of macro 'LOMSE_LOG_INFO'
   60 | #define LOMSE_LOG_INFO(...)             logger.log_info(__FILE__,__LINE__,__PRETTY_FUNCTION__,__VA_ARGS__)
      |                                                                                               ^~~~~~~~~~~
make[2]: *** [CMakeFiles/lenmus.dir/build.make:79: CMakeFiles/lenmus.dir/src/app/lenmus_app.cpp.o] Error 1
```

**Comment by cecilios** [comment]
LenMus sources include the latest code for Lomse library and this is the code that should be used to build LenMus. The LenMus CMakeLists.txt file includes an option (LENMUS_USE_LOMSE_SOURCES "Build LenMus using Lomse sources instead of using the library") that is ON by default, and should not be switched OFF unless the Lomse library to link to has been built using the latest Lomse code.

I develop Lomse as part of LenMus code, as I use LenMus to test Lomse. And it is much simpler for development and for users whising to build LenMus not to have to build and install first the Lomse library.

How do you build LenMus? I would recommend to do just:

```
mkdir my-build && cd my-build
cmake -G "Unix Makefiles" ../
make -j4
sudo make install
```

And forget about building the Lomse library.

**Comment by luigino** [comment]
I finally got around to test it and I can confirm that using an in-tree lomse fixes the build.
